inherit_from: "configs/rgbd/replica/base_config.yaml"
Dataset:
  dataset_path: "/root/Datasets/Replica/room1/"
  single_thread: False

Orbslam:
  vocab_file: "submodules/ORBSLAM3_PYTHON/extern/ORB_SLAM3/Vocabulary/ORBvoc.txt"
  settings_file: "submodules/ORBSLAM3_PYTHON/extern/ORB_SLAM3/Examples/RGB-D/Replica.yaml"
  sensor_type: 'rgbd'