inherit_from: "configs/mono/tum/base_config.yaml"

Dataset:
  dataset_path: "/root/Datasets/TUM/rgbd_dataset_freiburg3_long_office_household"
  Calibration:
    fx: 535.4
    fy: 539.2
    cx: 320.1
    cy: 247.6
    k1: 0.0
    k2: 0.0
    p1: 0.0
    p2: 0.0
    k3: 0.0
    width: 640
    height: 480
    depth_scale: 5000.0
    distorted: False

Orbslam:
  vocab_file: "submodules/ORBSLAM3_PYTHON/extern/ORB_SLAM3/Vocabulary/ORBvoc.txt"
  settings_file: "submodules/ORBSLAM3_PYTHON/extern/ORB_SLAM3/Examples/Monocular/TUM3.yaml"
  sensor_type: 'mono'