inherit_from: "configs/rgbd/tum/base_config.yaml"

Dataset:
  dataset_path: "/root/Datasets/TUM/rgbd_dataset_freiburg1_desk"
  Calibration:
    fx: 517.306408
    fy: 516.469215
    cx: 318.643040
    cy: 255.313989
    k1: 0.262383
    k2: -0.953104
    p1: -0.005358
    p2: 0.002628
    k3: 1.163314
    distorted: True
    width: 640
    height: 480
    depth_scale: 5000.0

Orbslam:
  vocab_file: "submodules/ORBSLAM3_PYTHON/extern/ORB_SLAM3/Vocabulary/ORBvoc.txt"
  settings_file: "submodules/ORBSLAM3_PYTHON/extern/ORB_SLAM3/Examples/RGB-D/TUM1.yaml"
  sensor_type: 'rgbd'