inherit_from: "configs/rgbd/tum/base_config.yaml"

Dataset:
  dataset_path: "/root/Datasets/TUM/rgbd_dataset_freiburg2_xyz"
  Calibration:
    fx: 520.90862
    fy: 521.007327
    cx: 325.141442
    cy: 249.701764
    k1: 0.2312
    k2: -0.7849
    p1: -0.0033
    p2: -0.0001
    k3: 0.9172
    distorted: True
    width: 640
    height: 480
    depth_scale: 5000.0

Orbslam:
  vocab_file: "submodules/ORBSLAM3_PYTHON/extern/ORB_SLAM3/Vocabulary/ORBvoc.txt"
  settings_file: "submodules/ORBSLAM3_PYTHON/extern/ORB_SLAM3/Examples/RGB-D/TUM2.yaml"
  sensor_type: 'rgbd'
